version: '3'
networks:
  public-net:
    internal: false
services:
  cppdemo:
    container_name: cppdemo
    build:
      context: .
      dockerfile: Dockerfile_cpp
    image:
      grpcdemo:cppdemo
    restart: "no"
    volumes: 
      - "./cpp_demo/protosource:/app/protosource"
    ports:  
      - "6001:1234"
    networks:
      - public-net
  pythondemo:
    container_name: pythondemo
    build:
      context: .
      dockerfile: Dockerfile_python
    image: 
      grpcdemo:pythondemo
    restart: "no"
    ports:
      - "6002:1234"
    networks:
      - public-net
